// packages/qj-monitor-react/src/view/index.tsx
import React, { Suspense } from 'react';
import {QjIcon} from '@brushes/components';
import classNames from 'classnames';
import {useMonitorReact} from '../hooks';
import { _ } from '@brushes/tools';
const {get} = _;

const MonitorComponent = (
  { materials = {} } :
  { materials: object}) => {

  const {
    actived,
    node,
    switchHandler,
    handlerImpl,
  } = useMonitorReact();

  return (
    <Suspense fallback={<p>加载中……</p>}>
      <div className={'default-iphone'}>
        <span className={'title'}>Iphone8首屏</span>
        <span className={'line'}></span>
      </div>
      {
        node.map(({id, props, type, name}, index: number) => {
          const MaterialsComponent = get(materials, type, () => <div></div>);
          return (
            <div key={id} className={'monitor-node'}>
              {
                actived !== id && (
                  <div className={classNames('component-name',
                    {
                      'component-name-left': index % 2,
                      'component-name-right': !(index % 2),
                    })}>
                    { name }
                  </div>
                )
              }
              <div onClick={() => switchHandler(id)}
                   className={classNames('content', {'actived': id === actived})}>
                <MaterialsComponent id={id} {...props}/>
              </div>
              {/*&& path === 'index'*/}
              {
                actived === id && node.length > 1 && (
                  <div onClick={(e) => handlerImpl(e, id, index)}>
                    <OperateJsx index={index} latest={node.length -1 === index}/>
                  </div>
                )
              }
            </div>
          );
        })
      }
    </Suspense>
  )
}

const OperateJsx = ({ index, latest }: { index: number; latest: boolean }) => {
  return (
    <div className={classNames('icon-operate')}>
      <QjIcon data-code={'delete'} name={'icon-DeleteOutlined'} style={{fontSize: 20}}/>
      {
        !latest && <QjIcon data-code={'xiayi'} name={'icon-xiayi'} style={{fontSize: 20}}/>
      }
      {
        index !== 0 && <QjIcon data-code={'shangyi'} name={'icon-shangyi'} style={{fontSize: 20}}/>
      }
    </div>
  )
}
export default MonitorComponent;

// packages/qj-monitor-vue/src/view/index.tsx
import {defineComponent} from "vue";
import classNames from 'classnames';
import useMonitorVue from '../hooks';
import { _ } from '@brushes/tools';
import { ToTopOutlined, VerticalAlignBottomOutlined, DeleteOutlined } from '@ant-design/icons-vue';
const { get, noop } = _;

const MonitorVue = defineComponent({
  name: 'Monitor',
  props: {
    materials: {
      type: Object,
      default: {}
    }
  },
  setup(props) {
    const { state, switchHandler, handlerImpl } = useMonitorVue();
    return {
      state,
      switchHandler,
      handlerImpl,
      materials: props.materials
    }
  },
  render() {
    const { node, actived } = this.state;
    return (
      <>
        <div className={'default-iphone'}>
          <span className={'title'}>Iphone8首屏</span>
          <span className={'line'}></span>
        </div>
        {
          node.map(({id, props, type, name}, index: number) => {
            const MaterialsComponent = get(this.materials, type, noop);
            return (
              <div key={id} class={'monitor-node'}>
                {
                  actived !== id ?
                    <div class={classNames('component-name',
                      {
                        'component-name-left': index % 2,
                        'component-name-right': !(index % 2),
                      })}>
                      { name }
                    </div>
                    :
                    <div
                      onClick={(e) => this.handlerImpl(e, id, index)}
                    >
                    <OperateJsx index={index} latest={node.length -1 === index}/>
                    </div>
                }
                <div
                  onClick={() => this.switchHandler(id)}
                     class={classNames('content', {'actived': id === actived})}>
                  <MaterialsComponent id={id} {...props}/>
                </div>
              </div>
            );
          })
        }
      </>
    )
  }
})

const OperateJsx = ({ index, latest }: { index: number; latest: boolean }) => {
  return (
    <div className={classNames('icon-operate')}>
      <DeleteOutlined data-code={'delete'} style={{fontSize: '20px'}}/>
      {
        !latest && <VerticalAlignBottomOutlined data-code={'xiayi'} style={{fontSize: '20px'}}/>
      }
      {
        index !== 0 && <ToTopOutlined data-code={'shangyi'} style={{fontSize: '20px'}}/>
      }
    </div>
  )
}

export default MonitorVue;
