// packages/s-material-react/src/components/Texts/index.tsx
import React, { useState, memo } from 'react';
import { View } from '@tarojs/components';

interface TextsType {
    defaultValue: Array<{
        title: string | number;
        subTitle: string | number;
    }>;
    margin?: number;
    cell: number;
    gap?: number;
    circular?: number;
}

const TextJsx: React.FC<TextsType> = ({ defaultValue = [], margin, circular, cell, gap = 10 }) => {
    const [list, setList] = useState<Array<any>>(defaultValue);
    return (
        <div
            style={{
                display: 'grid',
                gap,
                marginBottom: margin,
                gridTemplateColumns: `repeat(${cell}, 1fr)`
            }}
        >
            {list.map((item, index) => (
                <div
                    style={{
                        overflow: 'hidden',
                        borderRadius: circular === 1 ? 8 : 0
                    }}
                    className={'goods'}
                    key={index}
                >
                    <div className={'space'}>
                        <div className={'titleType'}>{item.title}</div>
                        <div className={'subTitle'}>{item.subTitle}</div>
                    </div>
                </div>
            ))}
        </div>
    );
};

export const Texts = memo(TextJsx);

// packages/s-material-vue/src/components/texts/index.tsx
import {defineComponent} from "vue";

const textProps = () => ({
  margin: {
    type: Number,
    default: undefined,
  },
  cell: Number,
  gap: {
    type: Number,
    default: 10,
  },
  circular: {
    type: Number,
    default: undefined,
  },
});

export const Texts = defineComponent({
  name: 'Texts',
  props: textProps(),
  setup(props, {emit, slots, attrs}) {

  },
  render() {
    const {
      margin,
      circular,
      cell,
      gap,
    } = this.$props;

    return (
      <view
        style={{
          display: 'grid',
          gap,
          marginBottom: margin,
          gridTemplateColumns: `repeat(${cell}, 1fr)`
        }}
      >
          <view
            style={{
              overflow: 'hidden',
              borderRadius: circular === 2 ? 0 : '16Px'
            }}
            class="goods"
          >
            <view class="space">
              <view class="titleType">{1231321}</view>
              <view class="subTitle">{4554344}</view>
            </view>
          </view>
      </view>
    )
  }
})
